### ISSUE TITLE
Improve architecture for easy update

### ISSUE THREAD

**Issue by Zizzamia** [Opentaste/bombolone#12]
For an easy update of bombolone, need separate all the main bombolone logic from
the app logic the user could write.

**Comment by devilicecream** [comment]
Maybe this shouldn't be closed yet. The *easy update* part is done, but the separation of the bombolone logic from the user app logic still needs to be done. How about opening another issue for that?

**Comment by Zizzamia** [comment]
Good idea! Open a new issue about the logic separation.
